# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/royal state/PycharmProjects/Arduino-Oscilloscope-1-Channel/src/MainUI.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1123, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.graphicsView = PlotWidget(self.centralwidget)
        self.graphicsView.setObjectName("graphicsView")
        self.verticalLayout_9.addWidget(self.graphicsView)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.MeterCheck = QtWidgets.QGroupBox(self.centralwidget)
        self.MeterCheck.setCheckable(True)
        self.MeterCheck.setChecked(False)
        self.MeterCheck.setObjectName("MeterCheck")
        self.label_11 = QtWidgets.QLabel(self.MeterCheck)
        self.label_11.setGeometry(QtCore.QRect(10, 10, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(11)
        self.label_11.setFont(font)
        self.label_11.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_11.setObjectName("label_11")
        self.verticalLayout_4.addWidget(self.MeterCheck)
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setTitle("")
        self.groupBox_4.setCheckable(False)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.SeePointsCheck = QtWidgets.QCheckBox(self.groupBox_4)
        self.SeePointsCheck.setObjectName("SeePointsCheck")
        self.horizontalLayout_15.addWidget(self.SeePointsCheck)
        self.DetectFreqCheck = QtWidgets.QCheckBox(self.groupBox_4)
        self.DetectFreqCheck.setObjectName("DetectFreqCheck")
        self.horizontalLayout_15.addWidget(self.DetectFreqCheck)
        self.verticalLayout_2.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.SaveDataButton = QtWidgets.QPushButton(self.groupBox_4)
        self.SaveDataButton.setAutoRepeatDelay(10)
        self.SaveDataButton.setAutoRepeatInterval(10)
        self.SaveDataButton.setObjectName("SaveDataButton")
        self.horizontalLayout_19.addWidget(self.SaveDataButton)
        self.SaveDataFileFormatCombo = QtWidgets.QComboBox(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SaveDataFileFormatCombo.sizePolicy().hasHeightForWidth())
        self.SaveDataFileFormatCombo.setSizePolicy(sizePolicy)
        self.SaveDataFileFormatCombo.setMaximumSize(QtCore.QSize(51, 20))
        self.SaveDataFileFormatCombo.setObjectName("SaveDataFileFormatCombo")
        self.SaveDataFileFormatCombo.addItem("")
        self.SaveDataFileFormatCombo.addItem("")
        self.SaveDataFileFormatCombo.addItem("")
        self.SaveDataFileFormatCombo.addItem("")
        self.horizontalLayout_19.addWidget(self.SaveDataFileFormatCombo)
        self.verticalLayout_2.addLayout(self.horizontalLayout_19)
        self.verticalLayout_4.addWidget(self.groupBox_4)
        self.horizontalLayout_5.addLayout(self.verticalLayout_4)
        self.SignelGenCheck = QtWidgets.QGroupBox(self.centralwidget)
        self.SignelGenCheck.setCheckable(True)
        self.SignelGenCheck.setChecked(True)
        self.SignelGenCheck.setObjectName("SignelGenCheck")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.SignelGenCheck)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.SigGenFreqSlider = QtWidgets.QSlider(self.SignelGenCheck)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SigGenFreqSlider.sizePolicy().hasHeightForWidth())
        self.SigGenFreqSlider.setSizePolicy(sizePolicy)
        self.SigGenFreqSlider.setMinimumSize(QtCore.QSize(119, 0))
        self.SigGenFreqSlider.setMinimum(0)
        self.SigGenFreqSlider.setMaximum(500)
        self.SigGenFreqSlider.setSingleStep(1)
        self.SigGenFreqSlider.setPageStep(1)
        self.SigGenFreqSlider.setProperty("value", 1)
        self.SigGenFreqSlider.setOrientation(QtCore.Qt.Horizontal)
        self.SigGenFreqSlider.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.SigGenFreqSlider.setTickInterval(10)
        self.SigGenFreqSlider.setObjectName("SigGenFreqSlider")
        self.horizontalLayout_9.addWidget(self.SigGenFreqSlider)
        self.SigGenFreqLabel = QtWidgets.QLabel(self.SignelGenCheck)
        self.SigGenFreqLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.SigGenFreqLabel.setObjectName("SigGenFreqLabel")
        self.horizontalLayout_9.addWidget(self.SigGenFreqLabel)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.SigGenPeriodSlider = QtWidgets.QSlider(self.SignelGenCheck)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SigGenPeriodSlider.sizePolicy().hasHeightForWidth())
        self.SigGenPeriodSlider.setSizePolicy(sizePolicy)
        self.SigGenPeriodSlider.setMinimumSize(QtCore.QSize(119, 0))
        self.SigGenPeriodSlider.setMinimum(0)
        self.SigGenPeriodSlider.setMaximum(200)
        self.SigGenPeriodSlider.setPageStep(1)
        self.SigGenPeriodSlider.setProperty("value", 100)
        self.SigGenPeriodSlider.setOrientation(QtCore.Qt.Horizontal)
        self.SigGenPeriodSlider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.SigGenPeriodSlider.setTickInterval(10)
        self.SigGenPeriodSlider.setObjectName("SigGenPeriodSlider")
        self.horizontalLayout_10.addWidget(self.SigGenPeriodSlider)
        self.SigGenPeriodLabel = QtWidgets.QLabel(self.SignelGenCheck)
        self.SigGenPeriodLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.SigGenPeriodLabel.setObjectName("SigGenPeriodLabel")
        self.horizontalLayout_10.addWidget(self.SigGenPeriodLabel)
        self.verticalLayout_3.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.SigGenDutyslider = QtWidgets.QSlider(self.SignelGenCheck)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SigGenDutyslider.sizePolicy().hasHeightForWidth())
        self.SigGenDutyslider.setSizePolicy(sizePolicy)
        self.SigGenDutyslider.setMinimumSize(QtCore.QSize(119, 0))
        self.SigGenDutyslider.setMinimum(0)
        self.SigGenDutyslider.setMaximum(100)
        self.SigGenDutyslider.setPageStep(1)
        self.SigGenDutyslider.setProperty("value", 25)
        self.SigGenDutyslider.setOrientation(QtCore.Qt.Horizontal)
        self.SigGenDutyslider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.SigGenDutyslider.setTickInterval(10)
        self.SigGenDutyslider.setObjectName("SigGenDutyslider")
        self.horizontalLayout_11.addWidget(self.SigGenDutyslider)
        self.SigGenDutyLabel = QtWidgets.QLabel(self.SignelGenCheck)
        self.SigGenDutyLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.SigGenDutyLabel.setObjectName("SigGenDutyLabel")
        self.horizontalLayout_11.addWidget(self.SigGenDutyLabel)
        self.verticalLayout_3.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_5.addWidget(self.SignelGenCheck)
        self.SamplingControlsFrame = QtWidgets.QGroupBox(self.centralwidget)
        self.SamplingControlsFrame.setObjectName("SamplingControlsFrame")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.SamplingControlsFrame)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.SampConrolDTScale = QtWidgets.QSlider(self.SamplingControlsFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SampConrolDTScale.sizePolicy().hasHeightForWidth())
        self.SampConrolDTScale.setSizePolicy(sizePolicy)
        self.SampConrolDTScale.setMinimumSize(QtCore.QSize(150, 0))
        self.SampConrolDTScale.setMinimum(0)
        self.SampConrolDTScale.setMaximum(200)
        self.SampConrolDTScale.setPageStep(1)
        self.SampConrolDTScale.setOrientation(QtCore.Qt.Horizontal)
        self.SampConrolDTScale.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.SampConrolDTScale.setTickInterval(10)
        self.SampConrolDTScale.setObjectName("SampConrolDTScale")
        self.horizontalLayout_12.addWidget(self.SampConrolDTScale)
        self.SampConrolDTLabel = QtWidgets.QLabel(self.SamplingControlsFrame)
        self.SampConrolDTLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.SampConrolDTLabel.setObjectName("SampConrolDTLabel")
        self.horizontalLayout_12.addWidget(self.SampConrolDTLabel)
        self.verticalLayout_7.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.SampControlQScale = QtWidgets.QSlider(self.SamplingControlsFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SampControlQScale.sizePolicy().hasHeightForWidth())
        self.SampControlQScale.setSizePolicy(sizePolicy)
        self.SampControlQScale.setMinimumSize(QtCore.QSize(160, 0))
        self.SampControlQScale.setMinimum(1)
        self.SampControlQScale.setMaximum(100)
        self.SampControlQScale.setPageStep(1)
        self.SampControlQScale.setProperty("value", 100)
        self.SampControlQScale.setOrientation(QtCore.Qt.Horizontal)
        self.SampControlQScale.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.SampControlQScale.setTickInterval(10)
        self.SampControlQScale.setObjectName("SampControlQScale")
        self.horizontalLayout_13.addWidget(self.SampControlQScale)
        self.SampControlQLabel = QtWidgets.QLabel(self.SamplingControlsFrame)
        self.SampControlQLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.SampControlQLabel.setObjectName("SampControlQLabel")
        self.horizontalLayout_13.addWidget(self.SampControlQLabel)
        self.verticalLayout_7.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.SamplingControlOnceButton = QtWidgets.QPushButton(self.SamplingControlsFrame)
        self.SamplingControlOnceButton.setCheckable(True)
        self.SamplingControlOnceButton.setObjectName("SamplingControlOnceButton")
        self.horizontalLayout_14.addWidget(self.SamplingControlOnceButton)
        self.SamplingControlVariousButton = QtWidgets.QPushButton(self.SamplingControlsFrame)
        self.SamplingControlVariousButton.setCheckable(True)
        self.SamplingControlVariousButton.setObjectName("SamplingControlVariousButton")
        self.horizontalLayout_14.addWidget(self.SamplingControlVariousButton)
        self.SamplingControlFlowButton = QtWidgets.QPushButton(self.SamplingControlsFrame)
        self.SamplingControlFlowButton.setCheckable(True)
        self.SamplingControlFlowButton.setObjectName("SamplingControlFlowButton")
        self.horizontalLayout_14.addWidget(self.SamplingControlFlowButton)
        self.verticalLayout_7.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_5.addWidget(self.SamplingControlsFrame)
        self.Channel1Check = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Channel1Check.setFont(font)
        self.Channel1Check.setAutoFillBackground(False)
        self.Channel1Check.setStyleSheet("")
        self.Channel1Check.setFlat(False)
        self.Channel1Check.setCheckable(True)
        self.Channel1Check.setObjectName("Channel1Check")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.Channel1Check)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(2, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.Channel1VoltsSlider = QtWidgets.QSlider(self.Channel1Check)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Channel1VoltsSlider.sizePolicy().hasHeightForWidth())
        self.Channel1VoltsSlider.setSizePolicy(sizePolicy)
        self.Channel1VoltsSlider.setMinimum(0)
        self.Channel1VoltsSlider.setMaximum(100)
        self.Channel1VoltsSlider.setPageStep(1)
        self.Channel1VoltsSlider.setProperty("value", 54)
        self.Channel1VoltsSlider.setOrientation(QtCore.Qt.Horizontal)
        self.Channel1VoltsSlider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.Channel1VoltsSlider.setTickInterval(10)
        self.Channel1VoltsSlider.setObjectName("Channel1VoltsSlider")
        self.horizontalLayout.addWidget(self.Channel1VoltsSlider)
        spacerItem1 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.Channel1VLabel = QtWidgets.QLabel(self.Channel1Check)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Channel1VLabel.sizePolicy().hasHeightForWidth())
        self.Channel1VLabel.setSizePolicy(sizePolicy)
        self.Channel1VLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.Channel1VLabel.setObjectName("Channel1VLabel")
        self.horizontalLayout.addWidget(self.Channel1VLabel)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(2, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.Channel1MsSlider = QtWidgets.QSlider(self.Channel1Check)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Channel1MsSlider.sizePolicy().hasHeightForWidth())
        self.Channel1MsSlider.setSizePolicy(sizePolicy)
        self.Channel1MsSlider.setMinimumSize(QtCore.QSize(130, 20))
        self.Channel1MsSlider.setMinimum(0)
        self.Channel1MsSlider.setMaximum(200)
        self.Channel1MsSlider.setPageStep(1)
        self.Channel1MsSlider.setProperty("value", 36)
        self.Channel1MsSlider.setOrientation(QtCore.Qt.Horizontal)
        self.Channel1MsSlider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.Channel1MsSlider.setTickInterval(10)
        self.Channel1MsSlider.setObjectName("Channel1MsSlider")
        self.horizontalLayout_2.addWidget(self.Channel1MsSlider)
        spacerItem3 = QtWidgets.QSpacerItem(2, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.Channel1MsLabel = QtWidgets.QLabel(self.Channel1Check)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Channel1MsLabel.sizePolicy().hasHeightForWidth())
        self.Channel1MsLabel.setSizePolicy(sizePolicy)
        self.Channel1MsLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.Channel1MsLabel.setObjectName("Channel1MsLabel")
        self.horizontalLayout_2.addWidget(self.Channel1MsLabel)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(0, 3, -1, 3)
        self.gridLayout.setHorizontalSpacing(2)
        self.gridLayout.setVerticalSpacing(1)
        self.gridLayout.setObjectName("gridLayout")
        self.Channel1MeasureButton = QtWidgets.QPushButton(self.Channel1Check)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Channel1MeasureButton.sizePolicy().hasHeightForWidth())
        self.Channel1MeasureButton.setSizePolicy(sizePolicy)
        self.Channel1MeasureButton.setMinimumSize(QtCore.QSize(60, 30))
        self.Channel1MeasureButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.Channel1MeasureButton.setCheckable(True)
        self.Channel1MeasureButton.setObjectName("Channel1MeasureButton")
        self.gridLayout.addWidget(self.Channel1MeasureButton, 0, 0, 1, 1)
        self.Channel1CurveButton = QtWidgets.QPushButton(self.Channel1Check)
        self.Channel1CurveButton.setMinimumSize(QtCore.QSize(0, 30))
        self.Channel1CurveButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.Channel1CurveButton.setCheckable(True)
        self.Channel1CurveButton.setObjectName("Channel1CurveButton")
        self.gridLayout.addWidget(self.Channel1CurveButton, 0, 1, 1, 1)
        self.Channel1TriggerButton = QtWidgets.QPushButton(self.Channel1Check)
        self.Channel1TriggerButton.setMinimumSize(QtCore.QSize(0, 30))
        self.Channel1TriggerButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.Channel1TriggerButton.setCheckable(True)
        self.Channel1TriggerButton.setDefault(False)
        self.Channel1TriggerButton.setFlat(False)
        self.Channel1TriggerButton.setObjectName("Channel1TriggerButton")
        self.gridLayout.addWidget(self.Channel1TriggerButton, 0, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout_5.addWidget(self.Channel1Check)
        self.groupBox_6 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_6.setCheckable(False)
        self.groupBox_6.setChecked(False)
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setContentsMargins(-1, -1, 3, -1)
        self.horizontalLayout_17.setSpacing(0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.ConfSerComPortCombo = QtWidgets.QComboBox(self.groupBox_6)
        self.ConfSerComPortCombo.setMinimumSize(QtCore.QSize(80, 0))
        self.ConfSerComPortCombo.setMaxVisibleItems(6)
        self.ConfSerComPortCombo.setObjectName("ConfSerComPortCombo")
        self.horizontalLayout_17.addWidget(self.ConfSerComPortCombo)
        self.ConfSerComPortLabel = QtWidgets.QLabel(self.groupBox_6)
        self.ConfSerComPortLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.ConfSerComPortLabel.setObjectName("ConfSerComPortLabel")
        self.horizontalLayout_17.addWidget(self.ConfSerComPortLabel)
        self.resetButton = QtWidgets.QPushButton(self.groupBox_6)
        self.resetButton.setMaximumSize(QtCore.QSize(25, 25))
        self.resetButton.setObjectName("resetButton")
        self.horizontalLayout_17.addWidget(self.resetButton)
        self.verticalLayout_6.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setContentsMargins(-1, -1, 3, -1)
        self.horizontalLayout_18.setSpacing(0)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.ConfSerBaoudRateCombo = QtWidgets.QComboBox(self.groupBox_6)
        self.ConfSerBaoudRateCombo.setMinimumSize(QtCore.QSize(80, 0))
        self.ConfSerBaoudRateCombo.setMaxVisibleItems(6)
        self.ConfSerBaoudRateCombo.setObjectName("ConfSerBaoudRateCombo")
        self.horizontalLayout_18.addWidget(self.ConfSerBaoudRateCombo)
        self.ConfSerBaoudRateLabel = QtWidgets.QLabel(self.groupBox_6)
        self.ConfSerBaoudRateLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.ConfSerBaoudRateLabel.setObjectName("ConfSerBaoudRateLabel")
        self.horizontalLayout_18.addWidget(self.ConfSerBaoudRateLabel)
        self.verticalLayout_6.addLayout(self.horizontalLayout_18)
        self.ConfSerPowerButton = QtWidgets.QPushButton(self.groupBox_6)
        self.ConfSerPowerButton.setEnabled(False)
        self.ConfSerPowerButton.setMinimumSize(QtCore.QSize(0, 31))
        self.ConfSerPowerButton.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.ConfSerPowerButton.setCheckable(True)
        self.ConfSerPowerButton.setAutoRepeatDelay(100)
        self.ConfSerPowerButton.setAutoRepeatInterval(10)
        self.ConfSerPowerButton.setObjectName("ConfSerPowerButton")
        self.verticalLayout_6.addWidget(self.ConfSerPowerButton)
        self.horizontalLayout_5.addWidget(self.groupBox_6)
        self.verticalLayout_9.addLayout(self.horizontalLayout_5)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1123, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.MeterCheck.setTitle(_translate("MainWindow", "Meter"))
        self.label_11.setText(_translate("MainWindow", "R :: 470 ohm (1)"))
        self.SeePointsCheck.setText(_translate("MainWindow", "See Points"))
        self.DetectFreqCheck.setText(_translate("MainWindow", "Detect Frequency"))
        self.SaveDataButton.setStatusTip(_translate("MainWindow", "Save Data to Selected File Type."))
        self.SaveDataButton.setText(_translate("MainWindow", "Save Data"))
        self.SaveDataButton.setShortcut(_translate("MainWindow", "Ctrl+Shift+S"))
        self.SaveDataFileFormatCombo.setStatusTip(_translate("MainWindow", "Select File Type to save Data to."))
        self.SaveDataFileFormatCombo.setItemText(0, _translate("MainWindow", "txt"))
        self.SaveDataFileFormatCombo.setItemText(1, _translate("MainWindow", "json"))
        self.SaveDataFileFormatCombo.setItemText(2, _translate("MainWindow", "csv"))
        self.SaveDataFileFormatCombo.setItemText(3, _translate("MainWindow", "xml"))
        self.SignelGenCheck.setTitle(_translate("MainWindow", "Signal Generator"))
        self.SigGenFreqLabel.setText(_translate("MainWindow", "f 50.0 Hz"))
        self.SigGenPeriodLabel.setText(_translate("MainWindow", "T 20.0 ms"))
        self.SigGenDutyLabel.setText(_translate("MainWindow", "Duty 25%"))
        self.SamplingControlsFrame.setTitle(_translate("MainWindow", "Sampling Contorls (100.0ms)"))
        self.SampConrolDTLabel.setText(_translate("MainWindow", "dt 1 ms"))
        self.SampControlQLabel.setText(_translate("MainWindow", "q 100 "))
        self.SamplingControlOnceButton.setText(_translate("MainWindow", "ONCE"))
        self.SamplingControlVariousButton.setText(_translate("MainWindow", "VARIOUS"))
        self.SamplingControlFlowButton.setText(_translate("MainWindow", "FLOW"))
        self.Channel1Check.setTitle(_translate("MainWindow", "Channel 1"))
        self.Channel1VLabel.setText(_translate("MainWindow", "2.5 V/Div"))
        self.Channel1MsLabel.setText(_translate("MainWindow", "900.0 ms/Div"))
        self.Channel1MeasureButton.setText(_translate("MainWindow", "Measure"))
        self.Channel1CurveButton.setText(_translate("MainWindow", "Curve"))
        self.Channel1TriggerButton.setText(_translate("MainWindow", "Trigger"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Configure Serial"))
        self.ConfSerComPortLabel.setText(_translate("MainWindow", "COM Port"))
        self.resetButton.setText(_translate("MainWindow", "R"))
        self.ConfSerBaoudRateLabel.setText(_translate("MainWindow", "Boud Rate"))
        self.ConfSerPowerButton.setText(_translate("MainWindow", "Power OFF"))
from pyqtgraph import PlotWidget
