# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/royal state/PycharmProjects/Arduino-Oscilloscope-1-Channel/src/MainUI.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1050, 800)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1050, 800))
        MainWindow.setMaximumSize(QtCore.QSize(1050, 800))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.groupBox_6 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_6.setGeometry(QtCore.QRect(860, 630, 181, 131))
        self.groupBox_6.setCheckable(False)
        self.groupBox_6.setChecked(False)
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setContentsMargins(-1, -1, 3, -1)
        self.horizontalLayout_17.setSpacing(0)
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.ConfSerComPortCombo = QtGui.QComboBox(self.groupBox_6)
        self.ConfSerComPortCombo.setMinimumSize(QtCore.QSize(80, 0))
        self.ConfSerComPortCombo.setObjectName(_fromUtf8("ConfSerComPortCombo"))
        self.ConfSerComPortCombo.addItem(_fromUtf8(""))
        self.horizontalLayout_17.addWidget(self.ConfSerComPortCombo)
        self.ConfSerComPortLabel = QtGui.QLabel(self.groupBox_6)
        self.ConfSerComPortLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.ConfSerComPortLabel.setObjectName(_fromUtf8("ConfSerComPortLabel"))
        self.horizontalLayout_17.addWidget(self.ConfSerComPortLabel)
        self.verticalLayout_6.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setContentsMargins(-1, -1, 3, -1)
        self.horizontalLayout_18.setSpacing(0)
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.ConfSerBaoudRateCombo = QtGui.QComboBox(self.groupBox_6)
        self.ConfSerBaoudRateCombo.setMinimumSize(QtCore.QSize(80, 0))
        self.ConfSerBaoudRateCombo.setObjectName(_fromUtf8("ConfSerBaoudRateCombo"))
        self.ConfSerBaoudRateCombo.addItem(_fromUtf8(""))
        self.horizontalLayout_18.addWidget(self.ConfSerBaoudRateCombo)
        self.ConfSerBaoudRateLabel = QtGui.QLabel(self.groupBox_6)
        self.ConfSerBaoudRateLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.ConfSerBaoudRateLabel.setObjectName(_fromUtf8("ConfSerBaoudRateLabel"))
        self.horizontalLayout_18.addWidget(self.ConfSerBaoudRateLabel)
        self.verticalLayout_6.addLayout(self.horizontalLayout_18)
        self.ConfSerPowerButton = QtGui.QPushButton(self.groupBox_6)
        self.ConfSerPowerButton.setMinimumSize(QtCore.QSize(0, 31))
        self.ConfSerPowerButton.setStyleSheet(_fromUtf8("background-color: rgb(255, 0, 0);"))
        self.ConfSerPowerButton.setCheckable(True)
        self.ConfSerPowerButton.setAutoRepeatDelay(100)
        self.ConfSerPowerButton.setAutoRepeatInterval(10)
        self.ConfSerPowerButton.setObjectName(_fromUtf8("ConfSerPowerButton"))
        self.verticalLayout_6.addWidget(self.ConfSerPowerButton)
        self.groupBox_4 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 690, 210, 70))
        self.groupBox_4.setTitle(_fromUtf8(""))
        self.groupBox_4.setCheckable(False)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.SeePointsCheck = QtGui.QCheckBox(self.groupBox_4)
        self.SeePointsCheck.setObjectName(_fromUtf8("SeePointsCheck"))
        self.horizontalLayout_15.addWidget(self.SeePointsCheck)
        self.DetectFreqCheck = QtGui.QCheckBox(self.groupBox_4)
        self.DetectFreqCheck.setObjectName(_fromUtf8("DetectFreqCheck"))
        self.horizontalLayout_15.addWidget(self.DetectFreqCheck)
        self.verticalLayout_2.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.SaveDataButton = QtGui.QPushButton(self.groupBox_4)
        self.SaveDataButton.setAutoRepeatDelay(10)
        self.SaveDataButton.setAutoRepeatInterval(10)
        self.SaveDataButton.setObjectName(_fromUtf8("SaveDataButton"))
        self.horizontalLayout_19.addWidget(self.SaveDataButton)
        self.SaveDataFileFormatCombo = QtGui.QComboBox(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SaveDataFileFormatCombo.sizePolicy().hasHeightForWidth())
        self.SaveDataFileFormatCombo.setSizePolicy(sizePolicy)
        self.SaveDataFileFormatCombo.setMaximumSize(QtCore.QSize(51, 20))
        self.SaveDataFileFormatCombo.setObjectName(_fromUtf8("SaveDataFileFormatCombo"))
        self.SaveDataFileFormatCombo.addItem(_fromUtf8(""))
        self.SaveDataFileFormatCombo.addItem(_fromUtf8(""))
        self.SaveDataFileFormatCombo.addItem(_fromUtf8(""))
        self.SaveDataFileFormatCombo.addItem(_fromUtf8(""))
        self.horizontalLayout_19.addWidget(self.SaveDataFileFormatCombo)
        self.verticalLayout_2.addLayout(self.horizontalLayout_19)
        self.MeterCheck = QtGui.QGroupBox(self.centralwidget)
        self.MeterCheck.setGeometry(QtCore.QRect(10, 630, 201, 51))
        self.MeterCheck.setCheckable(True)
        self.MeterCheck.setChecked(False)
        self.MeterCheck.setObjectName(_fromUtf8("MeterCheck"))
        self.label_11 = QtGui.QLabel(self.MeterCheck)
        self.label_11.setGeometry(QtCore.QRect(10, 10, 181, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(11)
        self.label_11.setFont(font)
        self.label_11.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.SignelGenCheck = QtGui.QGroupBox(self.centralwidget)
        self.SignelGenCheck.setGeometry(QtCore.QRect(220, 630, 191, 131))
        self.SignelGenCheck.setCheckable(True)
        self.SignelGenCheck.setChecked(False)
        self.SignelGenCheck.setObjectName(_fromUtf8("SignelGenCheck"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.SignelGenCheck)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.SigGenFreqSlider = QtGui.QSlider(self.SignelGenCheck)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SigGenFreqSlider.sizePolicy().hasHeightForWidth())
        self.SigGenFreqSlider.setSizePolicy(sizePolicy)
        self.SigGenFreqSlider.setMinimumSize(QtCore.QSize(119, 0))
        self.SigGenFreqSlider.setMinimum(0)
        self.SigGenFreqSlider.setMaximum(100)
        self.SigGenFreqSlider.setPageStep(1)
        self.SigGenFreqSlider.setProperty("value", 1)
        self.SigGenFreqSlider.setOrientation(QtCore.Qt.Horizontal)
        self.SigGenFreqSlider.setTickPosition(QtGui.QSlider.TicksAbove)
        self.SigGenFreqSlider.setTickInterval(10)
        self.SigGenFreqSlider.setObjectName(_fromUtf8("SigGenFreqSlider"))
        self.horizontalLayout_9.addWidget(self.SigGenFreqSlider)
        self.SigGenFreqLabel = QtGui.QLabel(self.SignelGenCheck)
        self.SigGenFreqLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.SigGenFreqLabel.setObjectName(_fromUtf8("SigGenFreqLabel"))
        self.horizontalLayout_9.addWidget(self.SigGenFreqLabel)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.SigGenPeriodSlider = QtGui.QSlider(self.SignelGenCheck)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SigGenPeriodSlider.sizePolicy().hasHeightForWidth())
        self.SigGenPeriodSlider.setSizePolicy(sizePolicy)
        self.SigGenPeriodSlider.setMinimumSize(QtCore.QSize(119, 0))
        self.SigGenPeriodSlider.setMinimum(0)
        self.SigGenPeriodSlider.setMaximum(200)
        self.SigGenPeriodSlider.setPageStep(10)
        self.SigGenPeriodSlider.setProperty("value", 100)
        self.SigGenPeriodSlider.setOrientation(QtCore.Qt.Horizontal)
        self.SigGenPeriodSlider.setTickPosition(QtGui.QSlider.TicksBelow)
        self.SigGenPeriodSlider.setTickInterval(10)
        self.SigGenPeriodSlider.setObjectName(_fromUtf8("SigGenPeriodSlider"))
        self.horizontalLayout_10.addWidget(self.SigGenPeriodSlider)
        self.SigGenPeriodLabel = QtGui.QLabel(self.SignelGenCheck)
        self.SigGenPeriodLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.SigGenPeriodLabel.setObjectName(_fromUtf8("SigGenPeriodLabel"))
        self.horizontalLayout_10.addWidget(self.SigGenPeriodLabel)
        self.verticalLayout_3.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.SigGenDutyslider = QtGui.QSlider(self.SignelGenCheck)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SigGenDutyslider.sizePolicy().hasHeightForWidth())
        self.SigGenDutyslider.setSizePolicy(sizePolicy)
        self.SigGenDutyslider.setMinimumSize(QtCore.QSize(119, 0))
        self.SigGenDutyslider.setMinimum(0)
        self.SigGenDutyslider.setMaximum(100)
        self.SigGenDutyslider.setPageStep(1)
        self.SigGenDutyslider.setProperty("value", 25)
        self.SigGenDutyslider.setOrientation(QtCore.Qt.Horizontal)
        self.SigGenDutyslider.setTickPosition(QtGui.QSlider.TicksBelow)
        self.SigGenDutyslider.setTickInterval(10)
        self.SigGenDutyslider.setObjectName(_fromUtf8("SigGenDutyslider"))
        self.horizontalLayout_11.addWidget(self.SigGenDutyslider)
        self.SigGenDutyLabel = QtGui.QLabel(self.SignelGenCheck)
        self.SigGenDutyLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.SigGenDutyLabel.setObjectName(_fromUtf8("SigGenDutyLabel"))
        self.horizontalLayout_11.addWidget(self.SigGenDutyLabel)
        self.verticalLayout_3.addLayout(self.horizontalLayout_11)
        self.SamplingControlsFrame = QtGui.QGroupBox(self.centralwidget)
        self.SamplingControlsFrame.setGeometry(QtCore.QRect(410, 630, 231, 131))
        self.SamplingControlsFrame.setObjectName(_fromUtf8("SamplingControlsFrame"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.SamplingControlsFrame)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.SampConrolDTScale = QtGui.QSlider(self.SamplingControlsFrame)
        self.SampConrolDTScale.setMinimum(0)
        self.SampConrolDTScale.setMaximum(200)
        self.SampConrolDTScale.setOrientation(QtCore.Qt.Horizontal)
        self.SampConrolDTScale.setTickPosition(QtGui.QSlider.TicksBelow)
        self.SampConrolDTScale.setTickInterval(10)
        self.SampConrolDTScale.setObjectName(_fromUtf8("SampConrolDTScale"))
        self.horizontalLayout_12.addWidget(self.SampConrolDTScale)
        self.SampConrolDTLabel = QtGui.QLabel(self.SamplingControlsFrame)
        self.SampConrolDTLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.SampConrolDTLabel.setObjectName(_fromUtf8("SampConrolDTLabel"))
        self.horizontalLayout_12.addWidget(self.SampConrolDTLabel)
        self.verticalLayout_7.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.SampControlQScale = QtGui.QSlider(self.SamplingControlsFrame)
        self.SampControlQScale.setMinimum(1)
        self.SampControlQScale.setMaximum(100)
        self.SampControlQScale.setProperty("value", 100)
        self.SampControlQScale.setOrientation(QtCore.Qt.Horizontal)
        self.SampControlQScale.setTickPosition(QtGui.QSlider.TicksBelow)
        self.SampControlQScale.setTickInterval(10)
        self.SampControlQScale.setObjectName(_fromUtf8("SampControlQScale"))
        self.horizontalLayout_13.addWidget(self.SampControlQScale)
        self.SampControlQLabel = QtGui.QLabel(self.SamplingControlsFrame)
        self.SampControlQLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.SampControlQLabel.setObjectName(_fromUtf8("SampControlQLabel"))
        self.horizontalLayout_13.addWidget(self.SampControlQLabel)
        self.verticalLayout_7.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.SamplingControlOnceButton = QtGui.QPushButton(self.SamplingControlsFrame)
        self.SamplingControlOnceButton.setCheckable(True)
        self.SamplingControlOnceButton.setObjectName(_fromUtf8("SamplingControlOnceButton"))
        self.horizontalLayout_14.addWidget(self.SamplingControlOnceButton)
        self.SamplingControlVariousButton = QtGui.QPushButton(self.SamplingControlsFrame)
        self.SamplingControlVariousButton.setCheckable(True)
        self.SamplingControlVariousButton.setObjectName(_fromUtf8("SamplingControlVariousButton"))
        self.horizontalLayout_14.addWidget(self.SamplingControlVariousButton)
        self.SamplingControlFlowButton = QtGui.QPushButton(self.SamplingControlsFrame)
        self.SamplingControlFlowButton.setCheckable(True)
        self.SamplingControlFlowButton.setObjectName(_fromUtf8("SamplingControlFlowButton"))
        self.horizontalLayout_14.addWidget(self.SamplingControlFlowButton)
        self.verticalLayout_7.addLayout(self.horizontalLayout_14)
        self.Channel1Check = QtGui.QGroupBox(self.centralwidget)
        self.Channel1Check.setGeometry(QtCore.QRect(640, 630, 221, 131))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Channel1Check.setFont(font)
        self.Channel1Check.setAutoFillBackground(False)
        self.Channel1Check.setStyleSheet(_fromUtf8(""))
        self.Channel1Check.setFlat(False)
        self.Channel1Check.setCheckable(True)
        self.Channel1Check.setObjectName(_fromUtf8("Channel1Check"))
        self.horizontalLayoutWidget = QtGui.QWidget(self.Channel1Check)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(5, 20, 211, 31))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem = QtGui.QSpacerItem(2, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.Channel1VoltsSlider = QtGui.QSlider(self.horizontalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Channel1VoltsSlider.sizePolicy().hasHeightForWidth())
        self.Channel1VoltsSlider.setSizePolicy(sizePolicy)
        self.Channel1VoltsSlider.setMinimumSize(QtCore.QSize(130, 20))
        self.Channel1VoltsSlider.setMinimum(0)
        self.Channel1VoltsSlider.setMaximum(100)
        self.Channel1VoltsSlider.setPageStep(1)
        self.Channel1VoltsSlider.setProperty("value", 54)
        self.Channel1VoltsSlider.setOrientation(QtCore.Qt.Horizontal)
        self.Channel1VoltsSlider.setTickPosition(QtGui.QSlider.TicksBelow)
        self.Channel1VoltsSlider.setTickInterval(10)
        self.Channel1VoltsSlider.setObjectName(_fromUtf8("Channel1VoltsSlider"))
        self.horizontalLayout.addWidget(self.Channel1VoltsSlider)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.Channel1VLabel = QtGui.QLabel(self.horizontalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Channel1VLabel.sizePolicy().hasHeightForWidth())
        self.Channel1VLabel.setSizePolicy(sizePolicy)
        self.Channel1VLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.Channel1VLabel.setObjectName(_fromUtf8("Channel1VLabel"))
        self.horizontalLayout.addWidget(self.Channel1VLabel)
        self.horizontalLayoutWidget_2 = QtGui.QWidget(self.Channel1Check)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(0, 50, 231, 31))
        self.horizontalLayoutWidget_2.setObjectName(_fromUtf8("horizontalLayoutWidget_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setSpacing(2)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem2 = QtGui.QSpacerItem(2, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.Channel1MsSlider = QtGui.QSlider(self.horizontalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Channel1MsSlider.sizePolicy().hasHeightForWidth())
        self.Channel1MsSlider.setSizePolicy(sizePolicy)
        self.Channel1MsSlider.setMinimumSize(QtCore.QSize(130, 20))
        self.Channel1MsSlider.setMinimum(0)
        self.Channel1MsSlider.setMaximum(200)
        self.Channel1MsSlider.setPageStep(1)
        self.Channel1MsSlider.setProperty("value", 36)
        self.Channel1MsSlider.setOrientation(QtCore.Qt.Horizontal)
        self.Channel1MsSlider.setTickPosition(QtGui.QSlider.TicksBelow)
        self.Channel1MsSlider.setTickInterval(10)
        self.Channel1MsSlider.setObjectName(_fromUtf8("Channel1MsSlider"))
        self.horizontalLayout_2.addWidget(self.Channel1MsSlider)
        spacerItem3 = QtGui.QSpacerItem(2, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.Channel1MsLabel = QtGui.QLabel(self.horizontalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Channel1MsLabel.sizePolicy().hasHeightForWidth())
        self.Channel1MsLabel.setSizePolicy(sizePolicy)
        self.Channel1MsLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.Channel1MsLabel.setObjectName(_fromUtf8("Channel1MsLabel"))
        self.horizontalLayout_2.addWidget(self.Channel1MsLabel)
        self.layoutWidget = QtGui.QWidget(self.Channel1Check)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 90, 181, 40))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 3, -1, 3)
        self.gridLayout.setHorizontalSpacing(2)
        self.gridLayout.setVerticalSpacing(1)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.Channel1MeasureButton = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Channel1MeasureButton.sizePolicy().hasHeightForWidth())
        self.Channel1MeasureButton.setSizePolicy(sizePolicy)
        self.Channel1MeasureButton.setMinimumSize(QtCore.QSize(60, 30))
        self.Channel1MeasureButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.Channel1MeasureButton.setCheckable(True)
        self.Channel1MeasureButton.setObjectName(_fromUtf8("Channel1MeasureButton"))
        self.gridLayout.addWidget(self.Channel1MeasureButton, 0, 0, 1, 1)
        self.Channel1CurveButton = QtGui.QPushButton(self.layoutWidget)
        self.Channel1CurveButton.setMinimumSize(QtCore.QSize(0, 30))
        self.Channel1CurveButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.Channel1CurveButton.setCheckable(True)
        self.Channel1CurveButton.setObjectName(_fromUtf8("Channel1CurveButton"))
        self.gridLayout.addWidget(self.Channel1CurveButton, 0, 1, 1, 1)
        self.Channel1TriggerButton = QtGui.QPushButton(self.layoutWidget)
        self.Channel1TriggerButton.setMinimumSize(QtCore.QSize(0, 30))
        self.Channel1TriggerButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.Channel1TriggerButton.setCheckable(True)
        self.Channel1TriggerButton.setDefault(False)
        self.Channel1TriggerButton.setFlat(False)
        self.Channel1TriggerButton.setObjectName(_fromUtf8("Channel1TriggerButton"))
        self.gridLayout.addWidget(self.Channel1TriggerButton, 0, 2, 1, 1)
        self.graphicsView = PlotWidget(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(10, 10, 1031, 601))
        self.graphicsView.setObjectName(_fromUtf8("graphicsView"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1050, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.groupBox_6.setTitle(_translate("MainWindow", "Configure Serial", None))
        self.ConfSerComPortCombo.setItemText(0, _translate("MainWindow", "COM 3", None))
        self.ConfSerComPortLabel.setText(_translate("MainWindow", "COM Port", None))
        self.ConfSerBaoudRateCombo.setItemText(0, _translate("MainWindow", "9600", None))
        self.ConfSerBaoudRateLabel.setText(_translate("MainWindow", "Boud Rate", None))
        self.ConfSerPowerButton.setText(_translate("MainWindow", "Power OFF", None))
        self.SeePointsCheck.setText(_translate("MainWindow", "See Points", None))
        self.DetectFreqCheck.setText(_translate("MainWindow", "Detect Frequency", None))
        self.SaveDataButton.setStatusTip(_translate("MainWindow", "Save Data to Selected File Type.", None))
        self.SaveDataButton.setText(_translate("MainWindow", "Save Data", None))
        self.SaveDataButton.setShortcut(_translate("MainWindow", "Ctrl+Shift+S", None))
        self.SaveDataFileFormatCombo.setStatusTip(_translate("MainWindow", "Select File Type to save Data to.", None))
        self.SaveDataFileFormatCombo.setItemText(0, _translate("MainWindow", "txt", None))
        self.SaveDataFileFormatCombo.setItemText(1, _translate("MainWindow", "json", None))
        self.SaveDataFileFormatCombo.setItemText(2, _translate("MainWindow", "csv", None))
        self.SaveDataFileFormatCombo.setItemText(3, _translate("MainWindow", "xml", None))
        self.MeterCheck.setTitle(_translate("MainWindow", "Meter", None))
        self.label_11.setText(_translate("MainWindow", "R :: 470 ohm (1)", None))
        self.SignelGenCheck.setTitle(_translate("MainWindow", "Signal Generator", None))
        self.SigGenFreqLabel.setText(_translate("MainWindow", "f 50.0 Hz", None))
        self.SigGenPeriodLabel.setText(_translate("MainWindow", "T 20.0 ms", None))
        self.SigGenDutyLabel.setText(_translate("MainWindow", "Duty 25%", None))
        self.SamplingControlsFrame.setTitle(_translate("MainWindow", "Sampling Contorls (100.0ms)", None))
        self.SampConrolDTLabel.setText(_translate("MainWindow", "dt 1 ms", None))
        self.SampControlQLabel.setText(_translate("MainWindow", "q 100 ", None))
        self.SamplingControlOnceButton.setText(_translate("MainWindow", "ONCE", None))
        self.SamplingControlVariousButton.setText(_translate("MainWindow", "VARIOUS", None))
        self.SamplingControlFlowButton.setText(_translate("MainWindow", "FLOW", None))
        self.Channel1Check.setTitle(_translate("MainWindow", "Channel 1", None))
        self.Channel1VLabel.setText(_translate("MainWindow", "2.5 V/Div", None))
        self.Channel1MsLabel.setText(_translate("MainWindow", "900.0 ms/Div", None))
        self.Channel1MeasureButton.setText(_translate("MainWindow", "Measure", None))
        self.Channel1CurveButton.setText(_translate("MainWindow", "Curve", None))
        self.Channel1TriggerButton.setText(_translate("MainWindow", "Trigger", None))

from pyqtgraph import PlotWidget
